[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Rithvik Redrouthu <rithvik.redrouthu@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
